openapi: 3.1.0
info:
  title: EMS Markdown Search API
  description: Searches a list of EMS .md files in a public GitHub repo and returns matching snippets.
  version: 1.0.0
servers:
  - url: https://sf-ems-api.onrender.com

paths:
  /search:
    get:
      operationId: searchMarkdownFiles
      summary: Search EMS Markdown files
      parameters:
        - name: q
          in: query
          required: true
          description: Keyword to search for
          schema:
            type: string
      responses:
        '200':
          description: List of matching file paths and snippets
          content:
            application/json:
              schema:
                type: object
                properties:
                  query:
                    type: string
                  matches:
                    type: array
                    items:
                      type: object
                      properties:
                        file:
                          type: string
                        snippet:
                          type: string
