openapi: 3.1.0
info:
  title: SF EMS Assistant API
  version: 1.2.0
  description: |
    API to search, summarize, quiz, compare, and analyze San Francisco EMS protocols, policies, and memos.

servers:
  - url: https://sf-ems-1.onrender.com

paths:
  /search:
    get:
      operationId: searchMarkdownFiles
      summary: Search for a keyword in all EMS documents
      parameters:
        - name: q
          in: query
          required: true
          description: Keyword or phrase to search for
          schema:
            type: string
      responses:
        '200':
          description: List of matched documents and snippet context
          content:
            application/json:
              schema:
                type: object
                properties:
                  query:
                    type: string
                  matches:
                    type: array
                    items:
                      type: object
                      properties:
                        file:
                          type: string
                        snippet:
                          type: string
                        url:
                          type: string

  /summarize:
    get:
      operationId: summarizeFile
      summary: Get full content of a file for GPT to summarize
      parameters:
        - name: file
          in: query
          required: true
          description: Path to the markdown file (e.g. Protocols/Airway - RSI.md)
          schema:
            type: string
      responses:
        '200':
          description: File content
          content:
            application/json:
              schema:
                type: object
                properties:
                  file:
                    type: string
                  content:
                    type: string
