openapi: 3.1.0
info:
  title: EMS Markdown Search API
  description: |
    Searches EMS protocols, policies, and memos hosted in a public GitHub repo and returns relevant results. 
    Also allows summarizing individual Markdown files.
  version: 1.1.0
servers:
  - url: https://sf-ems-1.onrender.com
paths:
  /search:
    get:
      operationId: searchMarkdownFiles
      summary: Search EMS Markdown documents
      parameters:
        - name: q
          in: query
          required: true
          description: Keyword or phrase to search for
          schema:
            type: string
      responses:
        '200':
          description: List of files and snippets containing the keyword
          content:
            application/json:
              schema:
                type: object
                properties:
                  query:
                    type: string
