openapi: 3.1.0
info:
  title: SF EMS Protocols Browser
  description: Access San Francisco EMS protocols, policies, and memos stored in a public GitHub repository.
  version: 1.0.0

servers:
  - url: https://api.github.com
    description: GitHub REST API

paths:
  /repos/{owner}/{repo}/contents/{path}:
    get:
      operationId: getFileOrDirectoryContents
      summary: Get the contents of a file or list files in a directory in the GitHub repo.
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
          example: nmatt101
        - name: repo
          in: path
          required: true
          schema:
            type: string
          example: sf-ems
        - name: path
          in: path
          required: true
          schema:
            type: string
          example: protocols
      responses:
        '200':
          description: File content or directory listing
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  path:
                    type: string
                  type:
                    type: string
                  content:
                    type: string
                  encoding:
                    type: string
        '404':
          description: File or directory not found

  /repos/{owner}/{repo}/git/trees/{tree_sha}:
    get:
      operationId: listAllFiles
      summary: Recursively list all files in the GitHub repo.
      parameters:
        - name: owner
          in: path
          required: true
          schema:
            type: string
          example: nmatt101
        - name: repo
          in: path
          required: true
          schema:
            type: string
          example: sf-ems
        - name: tree_sha
          in: path
          required: true
          schema:
            type: string
          example: main
        - name: recursive
          in: query
          required: false
          schema:
            type: integer
            enum: [1]
          example: 1
      responses:
        '200':
          description: Recursive tree of the repository
          content:
            application/json:
              schema:
                type: object
                properties:
                  tree:
                    type: array
                    items:
                      type: object
                      properties:
                        path:
                          type: string
                        type:
                          type: string
                        sha:
                          type: string
        '404':
          description: Repository or tree not found
